### ISSUE TITLE
Build not triggered on completion of some update sets

### ISSUE THREAD

**Issue by g-matharu** [bmoers/sn-cicd-integration#16]
When CICD property: **Ensure the Application records (sys_app) is in every update set.** is **enabled**, build does not trigger in below cases and the update set moves directly to 'Complete'

1. Update set is in 'global' scope and all the customer updates are also in 'global' scope
2. Update set in the scope of an application installed from Store or ServiceNow provided plugin

**Comment by bmoers** [comment]
The app lookup fails as "Global/global" and the ServiceNow Plugins are not in sys_app.
The query needs to be changed to point to sys_scope instead

**Comment by bmoers** [comment]
fixed by https://github.com/bmoers/sn-cicd-integration/pull/17
