### ISSUE TITLE
Import updateset "CICD Integration.xml", preview failed

### ISSUE THREAD

**Issue by gitlabbin** [bmoers/sn-cicd-integration#2]
Preview error:
 - Cannot commit Update Set 'CICD Integration - 1.1.2' because: Update scope id '733fb769db382f4076d6b94ffe96199f' is different than update set scope id 'global'. Resolve the problem before committing.

 - Could not find a record in sys_scope for column sys_scope referenced in this update

**Comment by bmoers** [comment]
Please take fixed version [CICD Integration - 1.1.3](https://github.com/bmoers/sn-cicd-integration/blob/master/update_set/CICD%20Integration.xml)

**Comment by gitlabbin** [comment]
👍 , V1.1.3 import succeed, going to close this
