### ISSUE TITLE
No XML records in pulled update set on target environment

### ISSUE THREAD

**Issue by bmoers** [bmoers/sn-cicd-integration#8]
The update set is created on the target environment but the related XML records are missing.

**Comment by jayakumarss** [comment]
We're still getting this error, is the issue is resolved? could you please help.

_400 - {"error":{"message":"Remote update-set not found with \\"remote_sys_id\\" a6313b59fc344b389edbe0e310f89fa2","detail":""},"status":"failure"}',_

**Comment by bmoers** [comment]
This issue is resolved in latest V3 and V4
What versions of CICD are you using?
Latest versions are
https://github.com/bmoers/sn-cicd-integration/releases/tag/v1.4.0
https://github.com/bmoers/sn-cicd/releases/tag/v4.0.10 resp https://github.com/bmoers/sn-cicd-example/tree/release/4

**Comment by bmoers** [comment]
closing as fixed in v4
